language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1/N5Vmg03wuDWPnwUDfX0kfSMkY3z0tvGKluF3KAxQyOE"